version: "3"

services:
  # InfluxDB
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - monitoring
    environment:
      INFLUXDB_DB:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_ADMIN_USER:
      INFLUXDB_ADMIN_PASSWORD:
  # Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER:
      GF_SECURITY_ADMIN_PASSWORD:

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  monitoring:
